language: python
python:
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get install -y gdal-bin
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test -c conda-forge python=$TRAVIS_PYTHON_VERSION gdal=2.2.4 scipy numpy psutil six lightgbm requests scikit-learn scikit-image
  - source activate test
  - pip install -U codecov
  - pip install gp_emulator
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
       pip install -U backports.functools_lru_cache;
    fi
  - pip install .
  
script:
  - pytest
